/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.connectorSQL.app;

import cat.uvic.teknos.m06.connectorSQL.list.LinkedList;

import static cat.uvic.teknos.m06.connectorSQL.utilities.StringUtils.join;
import static cat.uvic.teknos.m06.connectorSQL.utilities.StringUtils.split;
import static cat.uvic.teknos.m06.connectorSQL.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class Main {
    public static void main(String[] args) {
        ConnectionProperties conn = new ConnectionProperties("jdbc:mysql://localhost:3306/mysql","root","");


    }
}
